language: node_js
node_js:
  - "12"
  - "10"
  - "8"
install:
  - npm install -g grunt-cli
  # node 0.10 & 0.12 have race condition issues when running custom install scripts
  # this can cause phantomjs-prebuilt install script to fail with the error:
  # <Cannot find module 'boom'>
  # Seems related to: https://github.com/npm/npm/issues/8152
  # using <travis_retry> solves this.
  - travis_retry npm install
sudo: false
